version: '3'

services:

#  db:
#    image: postgres
#    restart: unless-stopped
#    environment:
#      POSTGRES_USER: YOUR_USERNAME
#      POSTGRES_PASSWORD: YOUR_PASSWORD
#      POSTGRES_DB: testdb
#    ports:
#      - 8082:5432
#    volumes:
#      - "./postgres/data:/var/lib/postgresql/data"

  backend:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
    ports:
        - 8081:8080
    restart: unless-stopped
      